#include "relay_transport.h"

#include <relayly/errors.hpp>

#include <spdlog/spdlog.h>
#include <yaml-cpp/yaml.h>

#include <cassert>
#include <filesystem>
#include <span>
#include <utility>

namespace {
// Matches relayly's own convention (sdk/cpp/README.md's quick start and Key
// management section): every official SDK reads/writes this same path and
// file format, so a device's key generated by one SDK works with another.
constexpr auto kDefaultPrivateKeyPath = "~/.relayly/device.key";
}  // namespace

RelayTransport::RelayTransport(std::string relay_url, RelayCredentials credentials)
    : relay_url_(std::move(relay_url)), credentials_(std::move(credentials)) {}

std::unique_ptr<RelayTransport> RelayTransport::from_config(std::string relay_url,
                                                             const std::string& config_path) {
    RelayCredentials credentials;

    std::error_code exists_error;
    if (!std::filesystem::exists(config_path, exists_error) || exists_error) {
        spdlog::warn(
            "relay credentials file '{}' not found; starting with empty credentials "
            "(see gateway/docs/relay-transport.md)",
            config_path);
        return std::make_unique<RelayTransport>(std::move(relay_url), std::move(credentials));
    }

    try {
        const YAML::Node root = YAML::LoadFile(config_path);
        if (root["device_id"]) credentials.device_id = root["device_id"].as<std::string>();
        if (root["private_key_path"])
            credentials.private_key_path = root["private_key_path"].as<std::string>();
        if (root["device_token"]) credentials.device_token = root["device_token"].as<std::string>();
    } catch (const YAML::Exception& parse_error) {
        spdlog::error("failed to parse relay credentials '{}': {}", config_path,
                      parse_error.what());
        credentials = RelayCredentials{};
    }

    return std::make_unique<RelayTransport>(std::move(relay_url), std::move(credentials));
}

RelayTransport::~RelayTransport() { stop(); }

void RelayTransport::start() {
    if (running_) return;

    if (credentials_.device_id.empty() || credentials_.device_token.empty()) {
        spdlog::error(
            "relay transport requires device_id and device_token (obtained via relayly's "
            "'POST /api/v1/devices' or the 'relayly pair <name>' CLI, see "
            "gateway/docs/relay-transport.md); not starting");
        return;
    }

    relayly::Options options;
    options.device_id = credentials_.device_id;
    options.device_token = credentials_.device_token;
    options.private_key = relayly::PrivateKey::LoadOrGenerate(
        credentials_.private_key_path.empty() ? kDefaultPrivateKeyPath : credentials_.private_key_path);
    options.on_ready = [this](const std::string& peer_id) { handle_peer_ready(peer_id); };
    options.on_peer_status = [this](const std::string& peer_id, const bool online) {
        handle_peer_status(peer_id, online);
    };
    options.on_message = [this](const relayly::Message& message) { handle_message(message); };
    options.on_disconnect = [relay_url = relay_url_](const std::string& reason) {
        spdlog::warn("relay transport lost connection to {}: {}", relay_url, reason);
    };
    options.on_reconnect = [relay_url = relay_url_]() {
        spdlog::info("relay transport reconnected to {}", relay_url);
    };

    try {
        client_ = relayly::Client::Connect(relay_url_, std::move(options));
    } catch (const relayly::Error& error) {
        spdlog::error("relay transport failed to connect to {}: {}", relay_url_, error.what());
        return;
    }

    running_ = true;
    spdlog::info("relay transport connected to {} (device_id={})", relay_url_,
                 credentials_.device_id);
}

void RelayTransport::stop() {
    if (!running_) return;

    if (client_) client_->Close();
    client_.reset();
    {
        std::lock_guard lock(peer_mutex_);
        current_peer_id_.reset();
    }
    running_ = false;
    spdlog::info("relay transport stopped");
}

bool RelayTransport::is_running() const { return running_; }

void RelayTransport::send(const ClientId client, const std::vector<uint8_t>& bytes) {
    std::string peer_id;
    {
        std::lock_guard lock(peer_mutex_);
        if (!current_peer_id_ || assigned_id_ != client) return;
        peer_id = *current_peer_id_;
    }
    if (!client_) return;
    try {
        client_->Send(peer_id, std::as_bytes(std::span(bytes)));
    } catch (const relayly::Error& error) {
        spdlog::warn("relay transport failed to send {} bytes to peer {}: {}", bytes.size(), peer_id,
                     error.what());
    }
}

void RelayTransport::broadcast(const std::vector<uint8_t>& bytes) {
    ClientId id = 0;
    {
        std::lock_guard lock(peer_mutex_);
        if (current_peer_id_) id = assigned_id_;
    }
    if (id != 0) send(id, bytes);
}

Transport::ClientRole RelayTransport::role(ClientId /*client*/) const {
    return ClientRole::kOperator;
}

relayly::PairCode RelayTransport::request_pair_code() {
    if (!client_) throw relayly::Error(relayly::ErrorCode::kClosed, "relay transport not started");
    return client_->RequestPairCode();
}

std::future<relayly::Peer> RelayTransport::accept_pair(const std::string& code) {
    if (!client_) throw relayly::Error(relayly::ErrorCode::kClosed, "relay transport not started");
    return client_->AcceptPair(code);
}

void RelayTransport::handle_peer_ready(const std::string& peer_id) {
    ClientId id;
    bool is_new;
    {
        std::lock_guard lock(peer_mutex_);
        is_new = !current_peer_id_.has_value() || *current_peer_id_ != peer_id;
        if (is_new) {
            id = next_client_id_.fetch_add(1);
            current_peer_id_ = peer_id;
            assigned_id_ = id;
        } else {
            id = assigned_id_;
        }
    }
    if (is_new) {
        spdlog::info("relay transport peer {} ready", peer_id);
        if (on_connect_) on_connect_(id);
    }
}

void RelayTransport::handle_peer_status(const std::string& peer_id, const bool online) {
    // on_ready, not the online transition here, is what marks a peer
    // "connected" for Transport's purposes (see class comment): a peer can
    // go online before its Noise session is ready to Send() to.
    if (online) return;

    ClientId id = 0;
    {
        std::lock_guard lock(peer_mutex_);
        if (current_peer_id_ && *current_peer_id_ == peer_id) {
            id = assigned_id_;
            current_peer_id_.reset();
        }
    }
    if (id != 0) {
        spdlog::info("relay transport peer {} offline", peer_id);
        if (on_disconnect_) on_disconnect_(id);
    }
}

void RelayTransport::handle_message(const relayly::Message& message) {
    ClientId id = 0;
    {
        std::lock_guard lock(peer_mutex_);
        if (current_peer_id_ && *current_peer_id_ == message.from) id = assigned_id_;
    }
    if (id != 0 && on_receive_) on_receive_(id, message.payload);
}

void RelayTransport::on_receive(ReceiveCallback callback) {
    assert(!running_ && "on_receive must be set before start()");
    on_receive_ = std::move(callback);
}

void RelayTransport::on_connect(ConnectCallback callback) {
    assert(!running_ && "on_connect must be set before start()");
    on_connect_ = std::move(callback);
}

void RelayTransport::on_disconnect(DisconnectCallback callback) {
    assert(!running_ && "on_disconnect must be set before start()");
    on_disconnect_ = std::move(callback);
}
