/**
 * Public surface of @nikx-tech/karshipta-console-core. Everything a consuming app
 * needs to render a live fleet map and wire it to a gateway: the store,
 * the transport, the wire types, and the display components. Onboarding
 * UI (empty-state, add-ward dialogs, connection panel) stays app-shell
 * only for now: it encodes this repo's self-host UX opinions, not a
 * general-purpose primitive yet. LocationPickerBar is a deliberate, narrow
 * exception: it's generic map-interaction chrome pairing with FleetMap's
 * own onMapClick escape hatch, not a self-host-vs-hosted opinion, so both
 * this app and a consuming app can share the same click-to-place UX.
 *
 * `protobufPackage` and `MessageFns` are deliberately not re-exported here:
 * ts-proto redeclares both per generated file, so re-exporting them from
 * more than one would collide.
 */

// wire types (proto/karshipta/v1/*.proto, generated by ts-proto)
export {
	WardClass,
	wardClassFromJSON,
	wardClassToJSON,
	FlightMode,
	flightModeFromJSON,
	flightModeToJSON,
	GpsFixType,
	gpsFixTypeFromJSON,
	gpsFixTypeToJSON,
	Severity,
	severityFromJSON,
	severityToJSON,
	WardOrigin,
	wardOriginFromJSON,
	wardOriginToJSON,
	type GeoPoint,
	type VelocityNed
} from './gen/karshipta/v1/common';
export type {
	WardInfo,
	Battery,
	Gps,
	FlightState,
	WardState,
	Event
} from './gen/karshipta/v1/telemetry';
export {
	CommandStatus,
	commandStatusFromJSON,
	commandStatusToJSON,
	MissionAction,
	missionActionFromJSON,
	missionActionToJSON,
	type ArmCommand,
	type DisarmCommand,
	type TakeoffCommand,
	type LandCommand,
	type ReturnToLaunchCommand,
	type GotoCommand,
	type StartMissionCommand,
	type PauseMissionCommand,
	type Command,
	type CommandAck,
	type MissionItem,
	type Mission,
	type MissionProgress
} from './gen/karshipta/v1/command';
export {
	WardConfigStatus,
	wardConfigStatusFromJSON,
	wardConfigStatusToJSON,
	FleetAckStatus,
	fleetAckStatusFromJSON,
	fleetAckStatusToJSON,
	ZoneType,
	zoneTypeFromJSON,
	zoneTypeToJSON,
	ZoneAckStatus,
	zoneAckStatusFromJSON,
	zoneAckStatusToJSON,
	FleetMissionStatus,
	fleetMissionStatusFromJSON,
	fleetMissionStatusToJSON,
	FleetMissionAckStatus,
	fleetMissionAckStatusFromJSON,
	fleetMissionAckStatusToJSON,
	FleetMissionStopAction,
	fleetMissionStopActionFromJSON,
	fleetMissionStopActionToJSON,
	WardMissionStatus,
	wardMissionStatusFromJSON,
	wardMissionStatusToJSON,
	type AddWard,
	type RemoveWard,
	type WardConfigAck,
	type Fleet,
	type CreateFleet,
	type RenameFleet,
	type DeleteFleet,
	type AddWardToFleet,
	type RemoveWardFromFleet,
	type FleetAck,
	type Zone,
	type CreateZone,
	type UpdateZone,
	type DeleteZone,
	type ZoneAck,
	type WardMissionPlan,
	type WardMissionState,
	type FleetMission,
	type CreateFleetMission,
	type FleetMissionAck,
	type StopFleetMission,
	type RemoveFleetMission,
	type UpdateFleetMissionRoutes
} from './gen/karshipta/v1/fleet';
export type { Envelope } from './gen/karshipta/v1/envelope';

// transport
export { WebSocketTransport, type FleetTransport, type TransportStatus } from './transport';

// store
export {
	fleet,
	isTerminal,
	isConfigTerminal,
	type Ward,
	type WardSource,
	type DraftWaypoint,
	type MissionDraft,
	type CommandTracker,
	type WardConfigTracker
} from './fleet-store.svelte';

// demo engine: a self-contained fake fleet, useful for any app's dev/demo mode
export { FakeGateway, FAKE_FLEET_CENTER, type DemoEngine } from './fake/fleet-sim';

// theme (light/dark, shared with any consuming app - see theme.css).
// ThemeToggle is a generic UI control over that shared store, not a
// self-host-vs-hosted opinion (same reasoning as LocationPickerBar above),
// so both this app's own right-panel.svelte and a consuming app's can place
// it themselves rather than each hand-rolling their own toggle.
export { themeStore, type Theme } from './theme.svelte';
export { default as ThemeToggle } from './components/theme-toggle.svelte';

// browser geolocation (shared by initial map centering and demo-ward placement)
export { locateOrFallback, type LatLon } from './geolocation';

// geozones (optional airspace-awareness layer)
export { geozoneStore } from './geozones/geozone-store.svelte';
export { OpenAipGeozoneSource } from './geozones/openaip';
export type { Geozone, GeozoneCategory, GeozoneSource, ViewportBounds } from './geozones/types';

// obstacles/airports (optional OpenAIP point layers, same opt-in-by-key
// shape as geozones above - all three share the request coordination in
// openaip/request-gate.ts, not exported since it's an internal detail no
// consuming app needs to reach directly).
export { obstacleStore } from './obstacles/obstacle-store.svelte';
export { OpenAipObstacleSource } from './obstacles/openaip';
export type { Obstacle, ObstacleCategory, ObstacleSource } from './obstacles/types';
export { airportStore } from './airports/airport-store.svelte';
export { OpenAipAirportSource } from './airports/openaip';
export type { Airport, AirportCategory, AirportSource } from './airports/types';

// cities (bundled reference data, not an OpenAIP layer - see
// cities/city-data.ts's own comment on why there's no key/rate-limit
// concern here, unlike the three layers above).
export { cityStore } from './cities/city-store.svelte';
export type { City } from './cities/types';

// aircraft (airplanes.live, no key/signup - see aircraft-store.svelte.ts
// and airplaneslive.ts's own comment on why this replaced an earlier
// OpenSky-based version: OpenSky's anonymous REST API sends a fixed CORS
// header that blocks every browser origin but its own, so it could never
// actually work client-side).
export { aircraftStore } from './aircraft/aircraft-store.svelte';
export { AirplanesLiveAircraftSource } from './aircraft/airplaneslive';
export { isAircraftEmergency } from './aircraft/types';
export type { Aircraft, AircraftCategory, AircraftSource } from './aircraft/types';

// earthquakes (USGS, fully open feed - see earthquake-store.svelte.ts).
export { earthquakeStore } from './earthquakes/earthquake-store.svelte';
export { UsgsEarthquakeSource } from './earthquakes/usgs';
export type { Earthquake, EarthquakeSource } from './earthquakes/types';

// wildfires (NASA FIRMS - needs its own MAP_KEY, same configure()/active
// shape as the OpenAIP layers, but an independent key/budget from theirs).
export { wildfireStore } from './wildfires/wildfire-store.svelte';
export { FirmsFireHotspotSource } from './wildfires/firms';
export type { FireHotspot, FireHotspotSource } from './wildfires/types';

// weather (Open-Meteo, fully open - see weather-store.svelte.ts on why
// this tracks the map center rather than a viewport like every layer
// above).
export { weatherStore } from './weather/weather-store.svelte';
export { OpenMeteoWeatherSource } from './weather/open-meteo';
export type { WeatherConditions, WeatherSource } from './weather/types';
export { weatherIconShape, weatherConditionLabel } from './weather/condition';
export type { WeatherIconShape } from './weather/condition';
export { default as WeatherIcon } from './components/weather-icon.svelte';

// units (Metric/Imperial display preference - see units-store.svelte.ts's
// own comment on this affecting read-only formatting only, never command
// inputs or the wire protocol). UnitsToggle is the same category of
// generic, no-self-host-opinion UI control as ThemeToggle above.
export { unitsStore, type UnitSystem } from './units/units-store.svelte';
export {
	formatAltitude,
	formatDistance,
	formatSpeed,
	formatVehicleSpeed,
	formatTemperature,
	formatPrecipitation,
	formatPressure
} from './units/format';
export { default as UnitsToggle } from './components/units-toggle.svelte';

// zones (operator-drawn keep-in/keep-out geofences, sent to the gateway -
// a different concept from geozoneStore's read-only airspace data above)
export { zoneStore, isZoneConfigTerminal } from './zones/zone-store.svelte';
export type { ZoneConfigTracker, ZoneDraft, LatLonPoint } from './zones/zone-store.svelte';

// fleet-groups (named groupings of wards within one session, plus
// fleet-wide mission assignment - a different concept from this file's own
// `fleet` store, which is the whole-account ward registry)
export {
	fleetGroups,
	isFleetConfigTerminal,
	isFleetMissionAckTerminal
} from './fleet-groups/fleet-groups-store.svelte';
export type {
	FleetConfigTracker,
	FleetMissionRequestTracker,
	MissionAssignmentDraft
} from './fleet-groups/fleet-groups-store.svelte';

// display components
export { default as FleetMap } from './components/fleet-map.svelte';
export { default as LocationPickerBar } from './components/location-picker-bar.svelte';
// Tabs is the icon-rail/tab-strip primitive left-rail.svelte and
// right-panel.svelte are both built from - unlike them, it carries zero
// self-host opinions (just ARIA tablist semantics + orientation), so a
// consuming app can build its own rail shell in the same visual/interaction
// language without forking either app-shell component wholesale.
export { default as Tabs, type TabItem } from './components/ui/tabs.svelte';
export { default as WardCard } from './components/ward-card.svelte';
// WardDetail is now WardTab (its former self-scrolling <section> chrome
// moved to right-panel.svelte's tabpanel wrapper, since the console's own
// shell now always owns that framing - see the shell restructure in
// right-panel.svelte). A consuming app that rendered WardDetail directly
// gets the same info line/dl/CommandPanel/MissionPanel content from WardTab.
export { default as WardTab } from './components/ward-tab.svelte';
export { default as WardStatusStrip } from './components/ward-status-strip.svelte';
export { default as CommandPanel } from './components/command-panel.svelte';
export { default as MissionPanel } from './components/mission-panel.svelte';
export { default as EventsFeed } from './components/events-feed.svelte';
export { default as ConfirmDialog } from './components/confirm-dialog.svelte';
// ZonesTab and MissionTab (which composes FleetMissionWizard/List/Row) are
// self-contained, store-driven content panels, the same category as
// WardTab/CommandPanel/MissionPanel above - not app-shell chrome. Unlike
// left-rail.svelte/right-panel.svelte (still unexported, see this file's
// own doc comment), neither encodes a self-host-vs-hosted opinion.
export { default as ZonesTab } from './components/zones-tab.svelte';
export { default as MissionTab } from './components/mission-tab.svelte';
export { default as FleetMissionWizard } from './components/fleet-mission-wizard.svelte';
export { default as FleetMissionList } from './components/fleet-mission-list.svelte';
export { default as FleetMissionRow } from './components/fleet-mission-row.svelte';
