/**
 * Public surface of @nikx-tech/karshipta-console-core. Everything a consuming app
 * needs to render a live fleet map and wire it to a gateway: the store,
 * the transport, the wire types, and the display components. Onboarding
 * UI (empty-state, add-ward dialogs, connection panel) stays app-shell
 * only for now: it encodes this repo's self-host UX opinions, not a
 * general-purpose primitive yet. LocationPickerBar is a deliberate, narrow
 * exception: it's generic map-interaction chrome pairing with FleetMap's
 * own onMapClick escape hatch, not a self-host-vs-hosted opinion, so both
 * this app and a consuming app can share the same click-to-place UX.
 *
 * `protobufPackage` and `MessageFns` are deliberately not re-exported here:
 * ts-proto redeclares both per generated file, so re-exporting them from
 * more than one would collide.
 */

// wire types (proto/karshipta/v1/*.proto, generated by ts-proto)
export {
	WardClass,
	wardClassFromJSON,
	wardClassToJSON,
	FlightMode,
	flightModeFromJSON,
	flightModeToJSON,
	GpsFixType,
	gpsFixTypeFromJSON,
	gpsFixTypeToJSON,
	Severity,
	severityFromJSON,
	severityToJSON,
	WardOrigin,
	wardOriginFromJSON,
	wardOriginToJSON,
	type GeoPoint,
	type VelocityNed
} from './gen/karshipta/v1/common';
export type {
	WardInfo,
	Battery,
	Gps,
	FlightState,
	WardState,
	Event
} from './gen/karshipta/v1/telemetry';
export {
	CommandStatus,
	commandStatusFromJSON,
	commandStatusToJSON,
	MissionAction,
	missionActionFromJSON,
	missionActionToJSON,
	type ArmCommand,
	type DisarmCommand,
	type TakeoffCommand,
	type LandCommand,
	type ReturnToLaunchCommand,
	type GotoCommand,
	type StartMissionCommand,
	type PauseMissionCommand,
	type Command,
	type CommandAck,
	type MissionItem,
	type Mission,
	type MissionProgress
} from './gen/karshipta/v1/command';
export {
	WardConfigStatus,
	wardConfigStatusFromJSON,
	wardConfigStatusToJSON,
	FleetAckStatus,
	fleetAckStatusFromJSON,
	fleetAckStatusToJSON,
	ZoneType,
	zoneTypeFromJSON,
	zoneTypeToJSON,
	ZoneAckStatus,
	zoneAckStatusFromJSON,
	zoneAckStatusToJSON,
	FleetMissionStatus,
	fleetMissionStatusFromJSON,
	fleetMissionStatusToJSON,
	FleetMissionAckStatus,
	fleetMissionAckStatusFromJSON,
	fleetMissionAckStatusToJSON,
	FleetMissionStopAction,
	fleetMissionStopActionFromJSON,
	fleetMissionStopActionToJSON,
	WardMissionStatus,
	wardMissionStatusFromJSON,
	wardMissionStatusToJSON,
	type AddWard,
	type RemoveWard,
	type WardConfigAck,
	type Fleet,
	type CreateFleet,
	type RenameFleet,
	type DeleteFleet,
	type AddWardToFleet,
	type RemoveWardFromFleet,
	type FleetAck,
	type Zone,
	type CreateZone,
	type UpdateZone,
	type DeleteZone,
	type ZoneAck,
	type WardMissionPlan,
	type WardMissionState,
	type FleetMission,
	type CreateFleetMission,
	type FleetMissionAck,
	type StopFleetMission,
	type RemoveFleetMission,
	type UpdateFleetMissionRoutes
} from './gen/karshipta/v1/fleet';
export type { Envelope } from './gen/karshipta/v1/envelope';

// transport
export { WebSocketTransport, type FleetTransport, type TransportStatus } from './transport';

// store
export {
	fleet,
	isTerminal,
	isConfigTerminal,
	type Ward,
	type WardSource,
	type DraftWaypoint,
	type MissionDraft,
	type CommandTracker,
	type WardConfigTracker
} from './fleet-store.svelte';

// demo engine: a self-contained fake fleet, useful for any app's dev/demo mode
export { FakeGateway, FAKE_FLEET_CENTER, type DemoEngine } from './fake/fleet-sim';

// theme (light/dark, shared with any consuming app - see theme.css)
export { themeStore, type Theme } from './theme.svelte';

// browser geolocation (shared by initial map centering and demo-ward placement)
export { locateOrFallback, type LatLon } from './geolocation';

// geozones (optional airspace-awareness layer)
export { geozoneStore } from './geozones/geozone-store.svelte';
export { OpenAipGeozoneSource } from './geozones/openaip';
export type { Geozone, GeozoneCategory, GeozoneSource, ViewportBounds } from './geozones/types';

// zones (operator-drawn keep-in/keep-out geofences, sent to the gateway -
// a different concept from geozoneStore's read-only airspace data above)
export { zoneStore, isZoneConfigTerminal } from './zones/zone-store.svelte';
export type { ZoneConfigTracker, ZoneDraft, LatLonPoint } from './zones/zone-store.svelte';

// fleet-groups (named groupings of wards within one session, plus
// fleet-wide mission assignment - a different concept from this file's own
// `fleet` store, which is the whole-account ward registry)
export {
	fleetGroups,
	isFleetConfigTerminal,
	isFleetMissionAckTerminal
} from './fleet-groups/fleet-groups-store.svelte';
export type {
	FleetConfigTracker,
	FleetMissionRequestTracker,
	MissionAssignmentDraft
} from './fleet-groups/fleet-groups-store.svelte';

// display components
export { default as FleetMap } from './components/fleet-map.svelte';
export { default as LocationPickerBar } from './components/location-picker-bar.svelte';
// Tabs is the icon-rail/tab-strip primitive left-rail.svelte and
// right-panel.svelte are both built from - unlike them, it carries zero
// self-host opinions (just ARIA tablist semantics + orientation), so a
// consuming app can build its own rail shell in the same visual/interaction
// language without forking either app-shell component wholesale.
export { default as Tabs, type TabItem } from './components/ui/tabs.svelte';
export { default as WardCard } from './components/ward-card.svelte';
// WardDetail is now WardTab (its former self-scrolling <section> chrome
// moved to right-panel.svelte's tabpanel wrapper, since the console's own
// shell now always owns that framing - see the shell restructure in
// right-panel.svelte). A consuming app that rendered WardDetail directly
// gets the same info line/dl/CommandPanel/MissionPanel content from WardTab.
export { default as WardTab } from './components/ward-tab.svelte';
export { default as WardStatusStrip } from './components/ward-status-strip.svelte';
export { default as CommandPanel } from './components/command-panel.svelte';
export { default as MissionPanel } from './components/mission-panel.svelte';
export { default as EventsFeed } from './components/events-feed.svelte';
export { default as ConfirmDialog } from './components/confirm-dialog.svelte';
// ZonesTab and MissionTab (which composes FleetMissionWizard/List/Row) are
// self-contained, store-driven content panels, the same category as
// WardTab/CommandPanel/MissionPanel above - not app-shell chrome. Unlike
// left-rail.svelte/right-panel.svelte (still unexported, see this file's
// own doc comment), neither encodes a self-host-vs-hosted opinion.
export { default as ZonesTab } from './components/zones-tab.svelte';
export { default as MissionTab } from './components/mission-tab.svelte';
export { default as FleetMissionWizard } from './components/fleet-mission-wizard.svelte';
export { default as FleetMissionList } from './components/fleet-mission-list.svelte';
export { default as FleetMissionRow } from './components/fleet-mission-row.svelte';
