/**
 * Public surface of @nikx-tech/karshipta-console-core. Everything a consuming app
 * needs to render a live fleet map and wire it to a gateway: the store,
 * the transport, the wire types, and the display components. Onboarding
 * UI (empty-state, add-vehicle dialogs, connection panel) stays app-shell
 * only for now: it encodes this repo's self-host UX opinions, not a
 * general-purpose primitive yet.
 *
 * `protobufPackage` and `MessageFns` are deliberately not re-exported here:
 * ts-proto redeclares both per generated file, so re-exporting them from
 * more than one would collide.
 */

// wire types (proto/karshipta/v1/*.proto, generated by ts-proto)
export {
	VehicleType,
	vehicleTypeFromJSON,
	vehicleTypeToJSON,
	FlightMode,
	flightModeFromJSON,
	flightModeToJSON,
	GpsFixType,
	gpsFixTypeFromJSON,
	gpsFixTypeToJSON,
	Severity,
	severityFromJSON,
	severityToJSON,
	type GeoPoint,
	type VelocityNed
} from './gen/karshipta/v1/common';
export type { VehicleInfo, Battery, Gps, VehicleState, Event } from './gen/karshipta/v1/telemetry';
export {
	CommandStatus,
	commandStatusFromJSON,
	commandStatusToJSON,
	MissionAction,
	missionActionFromJSON,
	missionActionToJSON,
	type ArmCommand,
	type DisarmCommand,
	type TakeoffCommand,
	type LandCommand,
	type ReturnToLaunchCommand,
	type GotoCommand,
	type StartMissionCommand,
	type PauseMissionCommand,
	type Command,
	type CommandAck,
	type MissionItem,
	type Mission,
	type MissionProgress
} from './gen/karshipta/v1/command';
export {
	VehicleConfigStatus,
	vehicleConfigStatusFromJSON,
	vehicleConfigStatusToJSON,
	type AddVehicle,
	type RemoveVehicle,
	type VehicleConfigAck
} from './gen/karshipta/v1/fleet';
export type { Envelope } from './gen/karshipta/v1/envelope';

// transport
export { WebSocketTransport, type FleetTransport, type TransportStatus } from './transport';

// store
export {
	fleet,
	isTerminal,
	isConfigTerminal,
	type Vehicle,
	type VehicleSource,
	type DraftWaypoint,
	type MissionDraft,
	type CommandTracker,
	type VehicleConfigTracker
} from './fleet-store.svelte';

// demo engine: a self-contained fake fleet, useful for any app's dev/demo mode
export { FakeGateway, FAKE_FLEET_CENTER, type DemoEngine } from './fake/fleet-sim';

// geozones (optional airspace-awareness layer)
export { geozoneStore } from './geozones/geozone-store.svelte';
export { OpenAipGeozoneSource } from './geozones/openaip';
export type { Geozone, GeozoneCategory, GeozoneSource, ViewportBounds } from './geozones/types';

// display components
export { default as FleetMap } from './components/fleet-map.svelte';
export { default as VehicleCard } from './components/vehicle-card.svelte';
export { default as VehicleDetail } from './components/vehicle-detail.svelte';
export { default as CommandPanel } from './components/command-panel.svelte';
export { default as MissionPanel } from './components/mission-panel.svelte';
export { default as EventsFeed } from './components/events-feed.svelte';
export { default as ConfirmDialog } from './components/confirm-dialog.svelte';
